### ISSUE TITLE
Create an executable (script) that gets installed and set up automatically

### ISSUE THREAD

**Issue by SylvainTakerkart** [INT-NIT/AnDOChecker#27]
We'd need to add a script that becomes an executable for the users and that gets automatically set-up when the package gets installed (e.g with pip).

A good example to follow seems to be the nipypecli executable script, that gets installed with nipype.

**Comment by Slowblitz** [comment]
Hi,

I have just updated the AnDOChecker package on pypi https://pypi.org/project/AnDOChecker/ so that once the "pip install" is done you can directly use ando as a bash script cf: the nipype package :

![image](https://user-images.githubusercontent.com/17256769/92326346-aafdd300-f051-11ea-800d-3d715407ddf4.png)

**Comment by SylvainTakerkart** [comment]
I've just tested on my local machine, it works like a charm ;)

**Comment by SylvainTakerkart** [comment]
The PR has been merged, we can close this issue! Thanks!
